name: MasterMerge
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Regex Merge
        uses: alagos/regex-merge@v1.1
        with:
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          headBranch: master
          notifyConflicts: true
